### ISSUE TITLE
Task2

### ISSUE THREAD

**Issue by alex-sadovsky** [SrujanAditya/NodeJs#2]
I need to mention that pipelined version is working correctly, while fullload-version has to be updated to my understanding.
Please review my comments, which I've left in your last commit:
https://github.com/SrujanAditya/NodeJs/commit/377d5c83e1255be69ea1c9fd29a7f648ccce949f

Also maybe you want to try to update fullload-version with `async`/`await` approach instead of promises?

**Comment by SrujanAditya** [comment]
Made the respective code changes
